# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /blog/:title/
relative_permalinks: true

# Setup
title:            'Bill Odom'
tagline:          'An Incredibly Exciting Website'
description:      'A place where Bill says stuff (or will, eventually)'
url:              http://billodom.com
baseurl:          /

author:
  name:           'Bill Odom'
  url:            https://twitter.com/wnodom

paginate:         5


# Custom

twitter: wnodom
github: wnodom

