# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Bill Odom'
tagline:          'Random Thoughts'
description:      'This is where the description will go. With luck, it will be more exciting than this placeholder.'
url:              http://billodom.com
baseurl:          /

author:
  name:           'Bill Odom'
  url:            https://twitter.com/wnodom

paginate:         5


# Custom

twitter: wnodom
github: wnodom

